### ISSUE TITLE
Ambient/night mode incorrectly drawn when tick marks and circles set to same color

### ISSUE THREAD

**Issue by lanrat** [Nxt3/IO_Classic_WatchFace#11]
I love this watch face and use it daily, however I "hide" the outside circle and tick-marks by setting them all to the same color. In normal mode this works great and looks like this:
![img_20180816_195708](https://user-images.githubusercontent.com/164192/44248291-90244180-a19e-11e8-8c66-dbc99ad22291.jpg)

However in ambient mode, a white circle outline is shown and is slightly lopsided and goes off screen. Ideally I'd like to hide it i ambient mode as well, but this looks like a bug and not a feature.
![img_20180816_195642](https://user-images.githubusercontent.com/164192/44248298-94e8f580-a19e-11e8-8b8e-2b26bde1956f.jpg)

**Comment by Nxt3** [comment]
Yeah that circle definitely shouldn't be shown. Lemme take a look tomorrow and I'll get back to you.

**Comment by Nxt3** [comment]
Okay this is why it's happening:

* When in Ambient mode, WearOS shifts stuff around the display to prevent burn-in. There is nothing I can do about this. That's why the circle is cut-off.

* Technically you're hiding the circles by setting the background color to the circle color so it's "hidden" but it's still being drawn. When you go into ambient mode, it draws as white since it has no way of knowing you were "hiding" it before.

The fix for this would be to add an option to hide all the circles. It's something I could implement, but I couldn't tell ya when I'll get around to it.
